### ISSUE TITLE
Limitations

### ISSUE THREAD

**Issue by schnittstabil** [sindresorhus/is-empty-iterable#1]
Maybe it is worth to note in `readme.md`, `is-empty-iterable` may _remove_ the first value:

``` js
const iterable = (function * () {
    yield 0;
    yield 1;
})();

isEmptyIterable(iterable);

Array.from(iterable)
//=> [1]
```

**Comment by sindresorhus** [comment]
No, what you have there is an Iterator. An Iterable initiates a new Iterator each time.

``` js
const iterable = {};

iterable[Symbol.iterator] = function * () {
    yield 0;
    yield 1;
};

isEmptyIterable(iterable);

Array.from(iterable)
//=> [0, 1]
```

**Comment by schnittstabil** [comment]
Aww, yes, I've oversimplified my example.

Nevertheless, it is not required to return the _same_ iterable each time, e.g. 

``` js
const iterable = {
    values: [0, 1],
    [Symbol.iterator]: function * () {
        if (this.values.length > 0) {
            yield this.values.shift();
        }
    }
};

isEmptyIterable(iterable);
Array.from(iterable)
//=> [1]
```

An example might be a event stream, which allows to iterate over new events – maybe much too theoretical:

``` js
for (const e of stream.newEvents) {
    // emptys newEvents
}

```

**Comment by schnittstabil** [comment]
Additionally:

``` js
const iterable = (function * () {
    yield 0;
    yield 1;
})();

iterable[Symbol.iterator]
// => [Function: [Symbol.iterator]]
```

Thus, `iterable` is an _Iterable_, it implements the [Iterable Interface](http://www.ecma-international.org/ecma-262/6.0/#sec-iterable-interface).

**Comment by sindresorhus** [comment]
Iterables can be dynamic, but seems like a bad practise to make them stateful. Iterables are meant to be able to be run concurrently. And you can't always control where they're consumed. What you have above there would be better as a Stream, which you usually consume once.

**Comment by schnittstabil** [comment]
> Iterables can be dynamic, but seems like a bad practise to make them stateful.

I totally agree, but is it worth to mention it in the `readme.md`?

**Comment by schnittstabil** [comment]
The same issue exists in many languages, it is often tackled by some _peekable thingy_, e.g. in Java [stackoverflow.com: How do I “peek” the next element on a Java Scanner?](http://stackoverflow.com/questions/4288643/how-do-i-peek-the-next-element-on-a-java-scanner/4288861#4288861)
– I'm not aware of a similar nodejs project…

**Comment by sindresorhus** [comment]
Nah, there are a gadzillion ways you can abuse JS. While your examples are valid, I don't think anyone would ever do that.

**Comment by sindresorhus** [comment]
Yes, I have a `iterable-peek` module locally, but it inhibits the same problem. I don't see it would be possible to work around stateful Iterables. I did a test where I save the peeked value and replay it when the generator is used again before getting the fresh values, but that will not work in all cases either as the fresh values might be incompatible with the replayed ones.
